# Generated by Django 5.1.3 on 2025-01-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_payment_date_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='payment_id',
        ),
    ]
