
###
POST http://127.0.0.1:8000/server/accounts/register/
Content-Type: application/json

{
  "user": {
    "username": "jsسe",
    "email": "joshس.doele.com",
    "password": "secسresw123"
  },
  "date_of_birth": "1985-11-10",
  "phone_number": "9876254210",
  "name": "Jodhn Doe",
  "gender": "male",
  "height": 180,
  "weight": 75
}
###


POST http://127.0.0.1:8000/server/accounts/login/
Content-Type: application/json

{
  "username": "jswoسe",
  "password": "secsuسresw123",
  "role":"patient"
}

###
### طلب للحصول على المرضى باسم معين
GET http://127.0.0.1:8000/server/patients/patient/Jodhn Doe/
Content-Type: application/json

###

GET http://127.0.0.1:8000/server/patients/notifications/1/
Content-Type: application/json



###
POST http://127.0.0.1:8000/server/patients/create_appointment_notification/1/

Content-Type: application/json

{
  "appointment_id": 1
}


### إنشاء حساب طبيب (Admin Only)
POST http://127.0.0.1:8000/server/doctors/create/
Authorization: Bearer d73ff900ef108d0be6fef8e2a53a49ae02ec4193
Content-Type: application/json

{
  "user": {
    "username": "dr.john",
    "email": "dr.john@example.com",
    "password": "password123"
  },
  "doctor": {
    "department":"orthopedics", 
    "specialization": "Cardiology",
    "years_of_experience": 10,
    "is_active": true
  }
}

---

### تسجيل دخول الطبيب
POST http://127.0.0.1:8000/server/accounts/login/
Content-Type: application/json

{
  "username": "dr.john",
  "password": "password123",
  "role": "doctor"
}

---

### تسجيل خروج الطبيب
POST http://127.0.0.1:8000/api/accounts/logout/
Authorization: Bearer <doctor_token>
Content-Type: application/json
###


GET http://127.0.0.1:8000/server/doctors/create/
Authorization: Bearer 55640433783fd2f3b683f64953e3e483c0ebb16a
