# Generated by Django 5.1.3 on 2024-12-28 16:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, error_messages={'unique': 'This phone number is already in use.'}, max_length=15, unique=True, validators=[accounts.models.validate_phone_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='patient', max_length=10),
        ),
    ]
