# Generated by Django 5.1.3 on 2024-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(),
        ),
    ]
