# Generated by Django 5.1.3 on 2025-01-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
