# Generated by Django 5.1.3 on 2024-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
