# Generated by Django 5.1.3 on 2024-11-30 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='recommended_treatment',
            new_name='prescribed_treatment',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
