# Generated by Django 5.1.3 on 2025-01-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='balance',
        ),
    ]
