# Generated by Django 5.1.3 on 2024-11-25 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_notification_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('orthopedics', 'عظمية'), ('gynecology', 'نسائية'), ('urology', 'بولية'), ('gastroenterology', 'هضمية'), ('nephrology', 'أمراض الكلى'), ('general_surgery and diabetic_foot', ' الجراحة العامة والقدم السكري'), ('ent', 'أمراض الأذن والأنف والحنجرة'), ('endocrinology', 'أمراض الغدد'), ('nutrition', 'التغذية'), ('dentistry', 'الأسنان وجراحتها'), ('cardiology', 'القلبية'), ('pulmonology', 'الأمراض الصدرية'), ('pediatrics', 'الأطفال'), ('dermatology', 'الجلدية')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.department')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
