# Generated by Django 5.1.3 on 2025-01-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_times',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('orthopedics', 'عظمية'), ('gynecology', 'نسائية'), ('urology', 'بولية'), ('gastroenterology', 'هضمية'), ('nephrology', 'أمراض الكلى'), ('general_surgery_and_diabetic_foot', ' الجراحة العامة والقدم السكري'), ('ent', 'أمراض الأذن والأنف والحنجرة'), ('endocrinology', 'أمراض الغدد'), ('nutrition', 'التغذية'), ('dentistry', 'الأسنان وجراحتها'), ('cardiology', 'القلبية'), ('pulmonology', 'الأمراض الصدرية'), ('pediatrics', 'الأطفال'), ('dermatology', 'الجلدية')], max_length=100),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctor')),
            ],
        ),
    ]
